blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^$', views.blog, name='BlogList'),
    url(r'^(?P<id>\d+)/$', views.post_detail, name='PostDetail'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.blog, name='BlogListByCategory'),
]

latina/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from latina import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^', include('pages.urls')),
    url(r'^blog/', include('blog.urls',  namespace='blog')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginsys/urls.py
from django.conf.urls import url
from loginsys.views import login, logout, register

urlpatterns = [
    url(r'^login/$', login),
    url(r'^logout/$', logout),
    url(r'^register/$', register),
]

pages/urls.py
from django.conf.urls import url
from pages.views import index, contact

urlpatterns = [
    url(r'^$', index),
    url(r'^contact/$', contact)
]

blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


# Create your models here.


# Модель категории
class Category(models.Model):
    category_name = models.CharField(max_length=50, unique=True, verbose_name="Название")
    category_slug = models.SlugField(max_length=200, db_index=True, unique=True, verbose_name="URL-название")
    category_parent = models.ForeignKey('self', related_name='category', verbose_name='Родительская категория',
                                        blank=True, null=True)

    def get_absolute_url(self):
        return reverse('blog:BlogListByCategory', args=[self.category_slug,])

    class Meta():
        db_table = 'category'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.category_name


class Post(models.Model):
    post_category = models.ForeignKey(Category, related_name='post', verbose_name="Категория")
    post_title = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    post_slug = models.SlugField(max_length=200, db_index=True, verbose_name="URL-название")
    post_img = models.ImageField(upload_to='blog_titels/', blank=True, null=True, verbose_name="Изображение")
    post_description = RichTextUploadingField(blank=True, verbose_name="Описание")
    post_short_description = models.TextField(max_length=300, blank=True, null=True, verbose_name="Короткое описание")
    post_available = models.BooleanField(default=True, verbose_name="Опубликованно")
    post_posted = models.DateField(auto_now_add=True, verbose_name="Дата публикации")


    class Meta():
        db_table = 'posts'
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-id']

    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse('blog:PostDetail', args=[self.id])

    def get_next(self):
        try:
            return Post.objects.all().filter(id__gt=self.id).exclude(id=self.id).order_by(
                'id')[:1].get()
        except Post.DoesNotExist:
            return

    def get_prev(self):
        try:
            return Post.objects.all().filter(id__lt=self.id).exclude(id=self.id).order_by(
                '-id')[:1].get()
        except Post.DoesNotExist:
            return

    def bit(self):
        if self.post_img:
            return u'<img src="/media/{}" width="100px"/>'.format(self.post_img)
        else:
            return u'(none)'
    bit.short_description = u'Изображение'
    bit.allow_tags = True

blog/forms.py
from django.forms import ModelForm
from .models import Comments

class CommentForm(ModelForm):
    class Meta():
        model = Comments
        fields = ['comments_text',]

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.


# страница блога (всех статтей)
def blog(request, category_slug=None,):
    category = None
    categories = Category.objects.all()
    post = Post.objects.filter(post_available=True)
    current_page = Paginator(post, 5)
    page = request.GET.get('page')

    if category_slug:
        category = get_object_or_404(Category, category_slug=category_slug)
        post = Post.objects.filter(post_category=category)
        current_page = Paginator(post, 5)
        page = request.GET.get('page')

    try:
        posts = current_page.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = current_page.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = current_page.page(current_page.num_pages)

    return render(request, 'blog/blog.html', {
        'categories': categories,
        'category': category,
        'posts': posts
    })


# Страница поста
def post_detail(request, id):
    post = get_object_or_404(Post, id=id, post_available=True)
    return render(request, 'blog/post_detail.html', {'post': post})

loginsys/views.py
from django.shortcuts import render_to_response, redirect
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.template.context_processors import csrf

# Create your views here.

def login (request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username','')
        password = request.POST.get('password','')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            args['login_error'] = 'Пользователь не найден'
            return render_to_response('login.html', args)
    else:
        return render_to_response('login.html', args)

def logout (request):
    auth.logout(request)
    return redirect('/')

def register(request):
    args = {}
    args.update(csrf(request))
    args['form'] = UserCreationForm()
    if request.POST:
        newuser_form = UserCreationForm(request.POST)
        if newuser_form.is_valid():
            newuser_form.save()
            newuser = auth.authenticate(username = newuser_form.cleaned_data['username'],
                                        password = newuser_form.cleaned_data['password2'])
            auth.login(request, newuser)
            return redirect('/')
        else:
            args['form'] = newuser_form
    return render_to_response('register.html', args)

pages/views.py
from django.shortcuts import render, render_to_response
from django.contrib import auth

# Create your views here.



def index(request):
    return render(request, 'pages/index.html', {'user_name': auth.get_user(request).username})

def contact(request):
    return render_to_response('pages/contact.html',)

blog/templates/post_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}
{{ post.post_title }}
{% endblock %}


{% block page_header %}
<!-- ----------------------------- Page Header ---------------------------- -->

{% if post.post_img %}
<header class="intro-header" style="background-image: url({{ post.post_img.url }})">
    <div class="blackout">
        {% else %}
        <header class="intro-header">
            {% endif %}
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        <div class="post-heading">
                            <h1>{{ post.post_title }}</h1>
                            <br>
                            <span class="meta">Написано для <a
                                    href="{{ BASE_DIR }}">Latina</a> {{ post.post_created }}<br>
                                    Категория: <a href="{{ post.post_category.get_absolute_url }}">
                                    {{ post.post_category }}</a></span>
                        </div>
                    </div>
                </div>
            </div>
            {% if post.post_img %}
    </div>
    {% endif %}
</header>
{% endblock %}

{% block content %}

<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {% autoescape off %}{{ post.post_description }}{% endautoescape %}
            </div>
        </div>
    </div>
</article>

{% endblock %}

loginsys/templates/login.html
{% extends 'base.html' %}

{% block login %}

<form action="/auth/login/" method="post">
    {% csrf_token %}
    <label for="username">Имя пользователя</label>
    <input type="text" name="username" id="username">
    <label for="password">Пароль</label>
    <input type="password" name="password" id="password">
    {% if login_error %}
        <label class="error">{{ login_error }}</label>
    {% endif %}
    <input class="button" type="submit" value="Войти">
    <div class=""><a href="/auth/register/">Регистрация</a></div>
</form>

{% endblock %}

loginsys/templates/register.html
{% extends 'base.html' %}

{% block login %}

<form action="/auth/register/" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="" type="submit" value="Зарегистрироваться">
</form>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="UTF-8">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}Secret Lazio{% endblock %}</title>
  
  {% block style %}
  <!-- Styles -->
  <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
  <link rel="stylesheet" href="{% static "css/clean-blog.css" %}">
  {% endblock %}

  {% block fonts %}
  <!-- Custom Fonts -->
  <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  {% endblock %}

</head>
<body>
    
   <!-- Navigation -->
    {% block navigation %}
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/">Secret Lazio</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" >
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/">Главная</a>
                    </li>
                    <li>
                        <a href="/blog">Блог</a>
                    </li>
                    <li>
                        <a href="/contact">Контакты</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    {% endblock %}

   {% block page_header %}
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Secret Lazio</h1>
                        <hr class="small">
                        <span class="subheading">побывай в местах, о которых пишут книги.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% endblock %}
    
    {% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Man must explore, and this is exploration at its greatest
                        </h2>
                        <h3 class="post-subtitle">
                            Problems look mighty small from 150 miles up
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 24, 2014</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
                        </h2>
                    </a>
                    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 18, 2014</p>
                </div>
                <hr>
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    {% endblock %}

    {% block footer %}
    <!-- Footer -->

    <footer>
        <div class="container">
            <div class="row">
                <hr>
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Secret Lazio 2017<br><a href="#">Back to top</a></p>
                </div>
            </div>
        </div>
    </footer>
    {% endblock %}
    
    {% block js %}
    <!-- jQuery -->
    <script src="{% static "js/jquery-2.1.4.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}></script>
    {% endblock %}

    {% block js_clean_blog %}
    <!-- Contact Form JavaScript -->
    <script src="{% static "js_clean_blog/jqBootstrapValidation.js" %}"></script>
    <script src="{% static "js_clean_blog/contact_me.js" %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static "js_clean_blog//clean-blog.min.js" %}"></script>
    {% endblock %}
    
</body>

</html>

templates/blog/blog.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
{% if category %} {{ category.name }} {% else %} Блог {% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-8">
            <h1>{% if category %}{{ category.name }}{% else %}Блог{% endif %}</h1>
            <hr>
            {% for post in posts %}
            <div class="post-preview">

                {% if post.post_img %}
                <a href="{{ post.get_absolute_url }}" class="post-img">
                    <div class="post-img" style="background: url({{ post.post_img.url }}) no-repeat center center">
                        <div class="post-title">
                            {{ post.post_title }}
                        </div>
                    </div>
                </a>
                {% else %}
                <div class="post-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.post_title }}</a>
                </div>
                {% endif %}

                <a href="{{ post.get_absolute_url }}">
                    <div class="post-subtitle"> {% autoescape off %}{% if post.post_short_description %}
                        {{ post.post_short_description }} {% endif %}{% endautoescape %}
                    </div>
                </a>

                <div class="post-meta">Написано для <a href="{{ BASE_DIR }}">Latina</a> {{ post.post_posted }}<br>
                    Категория: <a href="{{ post.post_category.get_absolute_url }}">{{ post.post_category }}</a>
                </div>
            </div>
            <hr>
            {% endfor %}

            <!-- Pager -->
            <ul class="pager">
                {% if posts.has_previous %}
                <li class="previous">
                    <a href="?page={{ posts.previous_page_number }}">&larr; Назад</a>
                </li>
                {% endif %}
                {% if posts.has_next %}
                <li class="next">
                    <a href="?page={{ posts.next_page_number }}">Вперед &rarr;</a>
                </li>
                {% endif %}
            </ul>
        </div>

        <!-- Category -->
        <div class="col-sm-3 col-sm-offset-1">
            <h1>Категории</h1>
            <ul>
                <li {% if not category %} class="selected" {% endif %}>
                    <a href="{% url "blog:BlogList" %}">Все</a>
                </li>
                {% for cat in categories %}
                <li {% if category.categoty_slug == cat.category_slug %} class="selected" {% endif %}>
                    <a href="{{ cat.get_absolute_url }}">{{ cat.category_name }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/blog/post_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}
{{ post.post_title }}
{% endblock %}


{% block page_header %}
<!-- ----------------------------- Page Header ---------------------------- -->

{% if post.post_img %}
<header class="intro-header" style="background-image: url({{ post.post_img.url }})">
    <div class="blackout">
        {% else %}
        <header class="intro-header">
            {% endif %}
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        <div class="post-heading">
                            <h1>{{ post.post_title }}</h1>
                            <br>
                            <span class="meta">Написано для <a
                                    href="{{ BASE_DIR }}">Latina</a> {{ post.post_created }}<br>
                                    Категория: <a href="{{ post.post_category.get_absolute_url }}">
                                    {{ post.post_category }}</a></span>
                        </div>
                    </div>
                </div>
            </div>
            {% if post.post_img %}
    </div>
    {% endif %}
</header>
{% endblock %}

{% block content %}
<!-- ----------------------------- Page Content ---------------------------- -->
<article>
    <div class="container">
        <div class="row">
            <!-- ----------------------------- Page Breadcrumbs ---------------------------- -->
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/blog">Блог</a></li>
                {% with cat=post.post_category %}
                {% if cat.category_parent %}
                <li class="breadcrumb-item">
                    <a href="{{cat.category_parent.get_bsolute_url}}">{{cat.category_parent.category_name}}</a>
                </li>
                {% endif %}
                <li class="breadcrumb-item active">{{cat.category_name}}</li>
                {% endwith %}
            </ol>
            <!-- ----------------------------- End Page Breadcrumbs ---------------------------- -->

            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {% autoescape off %}{{ post.post_description }}{% endautoescape %}
            </div>
        </div>
    </div>
</article>
<!-- ----------------------------- End Page Content ---------------------------- -->

<div class="entry-pagination">
    <ul class="pager">
        {% with prev=post.get_prev %}
        {% if prev %}
        <li><a href="{{ prev.get_absolute_url }}">← предыдущий</a></li>
        {% endif %}
        {% endwith %}
        {% with next=post.get_next %}
        {% if next %}
        <li><a href="{{ next.get_absolute_url }}">следующий →</a></li>
        {% endif %}
        {% endwith %}
    </ul>
    <!--close pager-->
</div>

{% endblock %}

templates/pages/contact.html
{% extends 'base.html' %}

{% load static %}

{% block page_header %}
<!-- ----------------------------- Page Header ---------------------------- -->

    <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Обратная связь</h1>
                        <hr class="small">
                        <span class="subheading">Есть вопросы? или пожелания?</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Email Address</label>
                            <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Phone Number</label>
                            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{% endblock %}